### ISSUE TITLE
[Bug]: dragging & dropping functionality

### ISSUE THREAD

**Issue by jmarkway** [Endward01/a_new_home#66] opened 2023-12-27 15:20 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.

### Contact Details

jmarkway@mobar.org

### What happened?

I am having issues with "changing the order of links and lists by dragging & dropping" functionality. The group and link dragging options are not visible when I right click the group or links, and dragging and dropping is not working.  I am using Firefox Developer 122.0b3, but I tried with Firefox 121.0 as well.

### a_new_home version

1.0

### What browsers are you seeing the problem on?

Firefox

**Comment by Endward01** [comment] 2023-12-27 19:11
Hi, 
i think you are referring to button that are shown in screenshots on firefox add-on website (screenshot below) witch show old context menu before 1.0 version ,
![image](https://github.com/Endward01/a_new_home/assets/100158911/8c2030fe-04bf-42a5-937b-95a7741e8832)

in new version there is diferent method to enable this functionality whitch is third icon from the left in contex menu 
![image](https://github.com/Endward01/a_new_home/assets/100158911/f5d4285c-360b-4d18-9b8a-5bb17b470aae)

please let me know if this is the problem then i will act accordingly

**Comment by Endward01** [comment] 2024-01-06 20:52
Closing this Report

-can't duplicate
-not a bug
-no anwser

**Closed by Endward01** 2024-01-06 20:52 UTC
Labels: bug
